version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vuetify
    versions:
    - 2.4.11
    - 2.4.6
    - 2.4.8
    - 2.4.9
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
  - dependency-name: sass-loader
    versions:
    - 11.0.1
