on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 🔨 Build Project
      run: |
        yarn install
        yarn build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.sessionmaster.app
        username: ${{ secrets.FTP_PASSWORD }}
        password: ${{ secrets.FTP_USERNAME }}
        dry-run: true
        local-dir: ./dist/
        server-dir: ./public_html/
